/**
 * Extend AdonisJS HttpContext with custom properties
 */
declare module '@adonisjs/core/http' {
  interface HttpContext {
    /**
     * CSP nonce generated by SecurityHeadersMiddleware
     * Used for Content Security Policy to allow specific inline scripts
     */
    nonce?: string
  }
}
