/**
 * Champion data for League of Legends
 *
 * This file loads champion data from champions.json (generated by the worker)
 * with a fallback to static data if the JSON doesn't exist yet.
 *
 * The worker syncs champion data from DDragon automatically.
 */

export interface Champion {
  id: number
  name: string
  key: string // DDragon key (e.g., "Aatrox", "AurelionSol")
}

// Try to load from generated JSON, fallback to static data
let championsData: { version: string; champions: Record<number, Champion> } | null = null

try {
  // This will be replaced at build time if the JSON exists
  championsData = require('./champions.json')
} catch (_error) {
  // JSON not generated yet (worker hasn't synced champions), will use static fallback
  // This is expected behavior during initial setup
}

// Static fallback data (subset of champions)
const STATIC_CHAMPIONS: Record<number, Champion> = {
  1: { id: 1, name: 'Annie', key: 'Annie' },
  103: { id: 103, name: 'Ahri', key: 'Ahri' },
  64: { id: 64, name: 'Lee Sin', key: 'LeeSin' },
  157: { id: 157, name: 'Yasuo', key: 'Yasuo' },
  238: { id: 238, name: 'Zed', key: 'Zed' },
  // Add more as needed for development
}

// Export the champions data
export const CHAMPIONS: Record<number, Champion> = championsData?.champions ?? STATIC_CHAMPIONS
export const DDRAGON_VERSION: string = championsData?.version ?? '14.24.1'

/**
 * Get champion name by ID
 */
export function getChampionName(championId: number): string {
  return CHAMPIONS[championId]?.name ?? `Champion ${championId}`
}

/**
 * Get champion DDragon key by ID (used for image URLs)
 */
export function getChampionKey(championId: number): string {
  return CHAMPIONS[championId]?.key ?? `Champion${championId}`
}

/**
 * Get champion icon URL (local images synced by worker)
 */
export function getChampionIconUrl(championId: number): string {
  const key = getChampionKey(championId)
  return `/images/champions/${key}.png`
}

/**
 * Get champion icon URL from DDragon (fallback)
 */
export function getChampionIconUrlDDragon(championId: number): string {
  const key = getChampionKey(championId)
  return `https://ddragon.leagueoflegends.com/cdn/${DDRAGON_VERSION}/img/champion/${key}.png`
}

/**
 * Get all champions as array
 */
export function getAllChampions(): Champion[] {
  return Object.values(CHAMPIONS)
}

/**
 * Search champions by name
 */
export function searchChampions(query: string): Champion[] {
  const lowerQuery = query.toLowerCase()
  return getAllChampions().filter(
    (champ) => champ.name.toLowerCase().includes(lowerQuery)
  )
}
